### ISSUE TITLE
Does not work at all (with existing solution)

### ISSUE THREAD

**Issue by joer33304** [mrlacey/TemplateStudio#7]
Template creates an empty project with no files:

![image](https://user-images.githubusercontent.com/2421310/157320601-e748fc94-f47c-46c5-8234-52797d8b099e.png)

![image](https://user-images.githubusercontent.com/2421310/157320624-4973a960-ade7-40f7-9efb-4ecad526992f.png)

Well, tried with a NEW project, there it works. Using it in an existing solution to add a new project results in the issues above

**Comment by mrlacey** [comment]
It inconsistently fails when adding to an existing solution.
I think I have a fix locally, and will try and get that out ASAP.

**Comment by mrlacey** [comment]
Out of interest, what are you using it for where you add to an existing solution?
The telemetry I've seen makes this a less common scenario. Although appreciably still valuable and valid.

I released it with this "known" intermittent issue because I expected few (if any) people to encounter it and you're the first.

**Comment by joer33304** [comment]
Well, I am adventures and try to use it with UNO :) So the idea was to just add it to the solution and copy over functionality step by step into the UNO app.

**Comment by mrlacey** [comment]
The latest version (0.5--released today) fixes this issue.
